name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Berlin
          template: classic
          base: header, activity, community, repositories
          config_animations: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_details: percentage

          plugin_stars: yes

          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_ignored: explorer, infographile, member, worker, verified

          plugin_lines: yes


